TOP=..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>



## Install templates
DB += pulseId_RX.template
DB += pulseId_TX.template
DB += perf.template




include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE
